---
version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - '9000:9000'
      - '8000:8000'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './data:/data'
    restart: unless-stopped
