---
- hosts: all
  become: yes

  vars_files:
    - inventory

  tasks:
    - name: Update Packagemanager
      apt:
        update_cache: yes

    - name: Install basic packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3
          - python3-pip
          - python3-apt
          - python3-setuptools
        state: latest
        update_cache: yes

    - name: Install required python libraries
      pip:
        name:
          - influxdb
          - requests

    - name: Download Docker installation script
      get_url:
        url: https://get.docker.com
        dest: /opt/docker_setup
        mode: 0755
      register: docker_script_download

    - name: Execute setup Docker script
      shell: /opt/docker_setup
      when: docker_script_download.changed

    - name: Import InfluxDB GPG signing key
      apt_key: url=https://repos.influxdata.com/influxdb.key state=present

    - name: Add InfluxDB repo
      apt_repository: repo='deb https://repos.influxdata.com/ubuntu trusty stable' state=present

    - name: Install InfluxDB packages
      apt: name=influxdb state=present

    # - name: Modify InfluxDB hostname
    #   replace: dest=/etc/opt/influxdb/influxdb.conf
    #     regexp='hostname = "localhost"'
    #     replace='hostname = "{{ ansible_hostname }}"'
    #     backup=yes

    - name: Start the InfluxDB service
      service: name=influxdb state=restarted

    - name: Create influxDB database
      community.general.influxdb_database:
        hostname: localhost
        database_name: weiss

    - name: Add grafana gpg key
      shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

    - name: Add grafana repo
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana

    - name: Install grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Enable and start grafana service
      service:
        name: grafana-server
        enabled: yes
        state: started
