---
version: '3'

services:
  grafana:
    image: grafana/grafana:7.4.3
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana_provisioning/:/etc/grafana/provisioning/
      - ./dashboards:/var/lib/grafana/dashboards
    # environment:
    #   - GF_AUTH_ANONYMOUS_ENABLED=true
    #   - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
    #   - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    #   - GF_AUTH_DISABLE_LOGIN_FORM=true
    #   - GF_SECURITY_ALLOW_EMBEDDING=true
    #   - GF_SERVER_DOMAIN=data.geox-geothermie.info
    #   - GF_SERVER_ROOT_URL=https://data.geox-geothermie.info/
    restart: unless-stopped

networks:
  default:
    external:
      name: data_backend
